import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import { Smartphone, Video, Pill, Shield } from "lucide-react";
const Index = () => {
    const navigate = useNavigate();
    return (_jsx("div", { className: "min-h-screen bg-gradient-to-br from-primary/10 via-background to-accent/10", children: _jsx("div", { className: "container mx-auto px-4 py-16", children: _jsxs("div", { className: "text-center space-y-8 max-w-3xl mx-auto", children: [_jsxs("div", { className: "space-y-4", children: [_jsx("h1", { className: "text-5xl md:text-6xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent", children: "MobiClinic" }), _jsx("p", { className: "text-xl md:text-2xl text-muted-foreground", children: "Quality healthcare, right from your phone" })] }), _jsxs("div", { className: "grid md:grid-cols-3 gap-6 mt-12", children: [_jsxs("div", { className: "p-6 rounded-xl bg-card shadow-[var(--shadow-card)]", children: [_jsx(Video, { className: "w-12 h-12 text-primary mx-auto mb-4" }), _jsx("h3", { className: "font-semibold mb-2", children: "Video Consultations" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Connect with certified doctors instantly" })] }), _jsxs("div", { className: "p-6 rounded-xl bg-card shadow-[var(--shadow-card)]", children: [_jsx(Pill, { className: "w-12 h-12 text-secondary mx-auto mb-4" }), _jsx("h3", { className: "font-semibold mb-2", children: "Prescriptions" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Digital prescriptions, available offline" })] }), _jsxs("div", { className: "p-6 rounded-xl bg-card shadow-[var(--shadow-card)]", children: [_jsx(Shield, { className: "w-12 h-12 text-accent mx-auto mb-4" }), _jsx("h3", { className: "font-semibold mb-2", children: "M-Pesa Payments" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Secure, convenient mobile payments" })] })] }), _jsxs(Button, { onClick: () => navigate("/auth"), size: "lg", className: "mt-8 bg-gradient-to-r from-primary to-primary/90 shadow-[var(--shadow-primary)] text-lg px-8", children: [_jsx(Smartphone, { className: "w-5 h-5 mr-2" }), "Get Started"] })] }) }) }));
};
export default Index;
